sudo: false
language: python
env:
  - ASSIGNMENT=assignment13
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install python=3.6 numpy scipy swig cmake
  - mkdir build; cd build; cmake ..; make
script:
  - ctest

