sudo: false
language: python
env:
  - ASSIGNMENT=assignment11
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge python=3.6 numpy scipy matplotlib cffi nbconvert ipython
  - "curl -H \"Authorization: token ${GH_TOKEN}\" -H 'Accept: application/vnd.github.v3.raw' -O --location \"https://api.github.com/repos/PGE383-HPC/${ASSIGNMENT}/contents/test.py\""
  - rm -f iterate_*.c iterate_*.so
  - gcc -fPIC -shared iterate.c -o iterate_abi.so 
  - export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH 
script:
  - python iterate_build.py
  - python test.py
